<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE easysso [
        <!ELEMENT easysso (clientType+,ignoreUrls?,ignoreResources?,ssoServer+,logoutUrl+,loginUrl+,ajaxFailureResponse?, jedisConfig?)>
        <!ELEMENT clientType      (#PCDATA)>
        <!ELEMENT ignoreUrls    (#PCDATA)>
        <!ELEMENT ignoreResources (#PCDATA)>
        <!ELEMENT ssoServer    (#PCDATA)>
        <!ELEMENT logoutUrl    (#PCDATA)>
        <!ELEMENT loginUrl    (#PCDATA)>
        <!ELEMENT ajaxFailureResponse (contentType?,code?,msg?)>
        <!ELEMENT contentType    (#PCDATA)>
        <!ELEMENT code    (#PCDATA)>
        <!ELEMENT msg    (#PCDATA)>
        <!ELEMENT jedisConfig (address+, password?, maxTotal?, maxIdle?, minIdle?, maxWaitMillis?)>
        <!ELEMENT address    (#PCDATA)>
        <!ELEMENT password    (#PCDATA)>
        <!ELEMENT maxTotal    (#PCDATA)>
        <!ELEMENT maxIdle    (#PCDATA)>
        <!ELEMENT minIdle    (#PCDATA)>
        <!ELEMENT maxWaitMillis    (#PCDATA)>
        ]>
<easysso>
    <!-- 应用类型 -->
    <clientType>web</clientType>
    <!-- 不需要验证的路径 -->
    <ignoreUrls>
        /login
        /sso/login
        /sso/loginPage
    </ignoreUrls>
    <!-- 不需要拦截的静态资源 -->
    <ignoreResources>
        .js
        .css
        .jpg
        .png
        .ico
        .html
    </ignoreResources>
    <!-- SSO Server地址 -->
    <ssoServer>http://127.0.0.1:8888/</ssoServer>
    <!-- 注销接口地址 -->
    <logoutUrl>/sso/logout</logoutUrl>
    <!-- 登录地址完整路径 -->
    <loginUrl>http://127.0.0.1:8888/sso/loginPage</loginUrl>
    <!-- ajax请求认证失败响应配置 -->
    <ajaxFailureResponse>
        <contentType>application/json</contentType>
        <code>401</code>
        <msg>用户未登录</msg>
    </ajaxFailureResponse>
    <!-- redis配置,客户端类型为app时需要配置 -->
    <!--
    <jedisConfig>
        <address>redis://127.0.0.1:6379</address>
        <maxTotal>200</maxTotal>
        <maxIdle>50</maxIdle>
        <minIdle>8</minIdle>
        <maxWaitMillis>10000</maxWaitMillis>
    </jedisConfig>
    -->
</easysso>